### ISSUE TITLE
Make seed node

### ISSUE THREAD

**Issue by stompesi** [radiusxyz/sequencer#10]
## What is a function?

> Please write a description of the function that the requested feature is trying to solve.

When the sequencer runs, the sequencer needs to know which proposer set to access. 
To do this, Seed should pass the sequencer a list of IPs of the sequencers participating in that proposer set.

## Todo

> Write down a description of why we need this feature.

### Subcommands
- [x] Init - (generate config file)
  - RPC endpoint
  - Provider address 
  - Contract address

- [x] Start - (run the seed node with config file)
  - ### Task (async)
  - [x] Initialize proposer set - init proposer set
  - [x] Register sequencer - add a sequencer into the proposer set
  - [x] Deregister sequencer - remove a sequencer into the proposer set
  ---
  - ### RPC (sync)
  - [x] Register sequencer - register sequencer IP address
  - [x] Get sequencers' IP List - get sequencers' IPs
