### ISSUE TITLE
Change naming

### ISSUE THREAD

**Issue by datactor** [radiusxyz/sequencer#27]
## Why need the refactoring?

> Please write a description.

Because we work together on code, we need to unify variable names.

## Todo

- [x] rollup_id -> full_node_id (because it has all states)
- [x] block information -> pending / finalized block
- [x] UserTransaction / SyncTransaction -> .*Request
- [x] tx -> transaction
- [x] Private key -> Signing key
- [x] Rpc Endpoint -> Rpc Url ( without json prefix)
  - [x] http => RPC Url
  - [x] WS => websocket url

## Reference (optional)
