### ISSUE TITLE
Merge RPC functions

### ISSUE THREAD

**Issue by stompesi** [radiusxyz/sequencer#6]
## What is a function?
> Please write a description on the function that the requested feature is trying to solve.

We need to port sequencer rpc functions to sequencer-framework.

## Todo
> Write down a description on why do we need this feature.

- [x] #13 

### Rollup
- [x] #7
- [x] #9

### Raw transaction
- [x] send_raw_transaction
- [x] get_raw_transaction
- [x] get_raw_transaction_list(get block)

### Encrypted transaction
- [x] send_encrypted_transaction
- [x] get_encrypted_transaction
- [x] get_encrypted_transaction_list(get block)

## Reference (optional)
