### ISSUE TITLE
eth_functions

### ISSUE THREAD

**Issue by datactor** [radiusxyz/sequencer#8]
## What is a function?

> Please write a description of the function that the requested feature is trying to solve.

RPC call forwarding the methods below
 
## Todo
> Write down a description on why do we need this feature.
- [x] eth_block_number
- [x] eth_call
- [x] eth_chain_id
- [x] eth_estimate_gas
- [x] eth_fee_history
- [x] eth_gas_price
- [x] eth_get_balance
- [x] eth_get_block_by_number
- [x] eth_get_code
- [x] eth_get_transaction_count
- [x] eth_get_transaction_receipt
- [x] eth_send_raw_transaction
- [x] eth_net_version
